service:
  name: notification-service

plugins:
  - serverless-bundle
  - serverless-pseudo-parameters

provider:
  name: aws
  runtime: nodejs12.x
  memorySize: 256
  region: ${opt:region, 'us-east-1'}
  stage: ${opt:stage, 'dev'}
  tags:
    Owner: serverless_node_aws_user
  stackTags:
    Owner: serverless_node_aws_user
  iamRoleStatements:
    - ${file(iam/LambdaRoles.yml):SendMail}

functions:
  sendMail:
    handler: src/handlers/sendMail.handler
